export const login_Actions= {
	login_SignIn :{
    NEW:"LOGIN_ACCOUNT_NEW",
    POST:"LOGIN_ACCOUNT_POST",
		AUTHORIZED: "LOGIN_ACCOUNT_AURHORIZED",
		NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
		FAILURE: "LOGIN_ACCOUNT_FAILURE",
		SIGN0UT:"SIGN0UT"
	}
}


export const login_Status ={
	login_SignIn :{
    NEW:"LOGIN_ACCOUNT_NEW",
    AUTHORIZED: "LOGIN_ACCOUNT_AURHORIZED",
		NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
		FAILURE: "LOGIN_ACCOUNT_FAILURE",
		LOADING:"LOGIN_ACCOUNT_LOADING",
		SIGN0UT:"SIGN0UT"
	}


}
